version: "3"

volumes:
  dbdata:
    name: "wikijs-dbdata"
    #external: true
  content:
    name: "wikijs-content"
    #external: true

services:
  database:
    image: docker.io/postgres
    container_name: wikijs-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    ports: "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - dbdata:/var/lib/postgresql/data:Z

  # database:
  #   image: docker.io/mariadb
  #   container_name: wikijs-db
  #   environment:
  #     MARIADB_DATABASE: ${DB_NAME}
  #     MARIADB_USER: ${DB_USER}
  #     MARIADB_PASSWORD: ${DB_PASSWORD}
  #     MARIADB_RANDOM_ROOT_PASSWORD: yes
  #   restart: unless-stopped
  #   ports: "${MYSQL_PORT}:${MYSQL_PORT}"
  #   volumes:
  #     - dbdata:/var/lib/mysql:Z

  # database:
  #   image: docker.io/mysql
  #   container_name: wikijs-db
  #   environment:
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_RANDOM_ROOT_PASSWORD: yes
  #   restart: unless-stopped
  #   ports: "${MYSQL_PORT}:${MYSQL_PORT}"
  #   volumes:
  #     - dbdata:/var/lib/mysql:Z

  # database:
  #   image: docker.io/nouchka/sqlite3
  #   container_name: wikijs-db
  #   restart: unless-stopped
  #   volumes:
  #     - dbdata:/root/db:Z

  wiki:
    image: docker.io/requarks/wiki
    container_name: wikijs
    depends_on:
      - database
    environment:
      DB_TYPE: ${DB_TYPE}
      DB_PORT: ${DB_PORT}
      DB_HOST: wikijs-db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_FILEPATH: ${SQLITE_DB}
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:${WIKIJS_PORT}"
    volumes:
      - content:/wiki/data/content:Z
